FROM docker.io/library/golang:1.24-alpine3.21 AS base

RUN apk --no-cache add openssh-client build-base linux-headers git bash ca-certificates libstdc++ libc-dev gcc snappy-dev gflags-dev zlib-dev bzip2-dev lz4-dev zstd-dev perl cmake


FROM base AS test

WORKDIR /app

ADD deps deps
ADD Makefile Makefile
RUN make rocksdb

ADD go.mod go.mod
ADD go.sum go.sum
ADD erigon-lib/go.mod erigon-lib/go.mod
ADD erigon-lib/go.sum erigon-lib/go.sum
RUN go mod download

ADD . .

RUN make test-rocksdb

ENTRYPOINT ["echo", "done"]
