name: test-rpc

on:
  push:
    branches:
      - ns/wrk-rpc-test
  #  schedule:
  #    - cron: '*/5 * * * *'
  workflow_dispatch:
    with:
      ref: ns/wrk-rpc-test

jobs:
  eth-namespace:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install wrk
        run: |
          git clone https://github.com/wg/wrk.git
          cd wrk
          make
          cp wrk /usr/local/bin

      - name: eth_wrk
        run: chmod u+x eth.sh && bash eth.sh
        working-directory: tests/stress-testing/scripts/eth

      - name: Install wrk2
        run: |
          git clone https://github.com/giltene/wrk2.git
          cd wrk2
          make
          cp wrk /usr/local/bin/wrk2

      - name: eth_wrk2
        run: chmod u+x eth.sh && bash eth.sh
        working-directory: tests/stress-testing/scripts/eth